version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 791860731934.dkr.ecr.us-east-1.amazonaws.com
      - REPO_URI=791860731934.dkr.ecr.us-east-1.amazonaws.com/dev-app
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPO_URI:latest .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image to ECR...
      - docker push $REPO_URI:latest
      - docker push $REPO_URI:$IMAGE_TAG
      - echo '[{"name":"dev-app","imageUri":"'$REPO_URI':'$IMAGE_TAG'"}]' > imagedefinitions.json
      - echo Writing image definitions file...
      - cat imagedefinitions.json


artifacts:
    files: imagedefinitions.json
